services:   
  backend:
    build: ./Backend-main/odc
    container_name: BackendCont
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    build: ./Frontend-main/
    container_name: FrontendCont
    ports:
      - "8081:80"
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: odc
      POSTGRES_PASSWORD: odc123
      POSTGRES_DB: odcdb
    ports:
      - 5431:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  migrate:
    build: ./Backend-main/odc
    command: python manage.py migrate
    depends_on:
      - db
      - backend
volumes:
  postgres_data:
